# Generated by Django 2.1 on 2018-10-29 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import select2.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abwesenheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Arbeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arbeitseinsatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbeitstyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True)),
                ('datum', models.DateField()),
                ('pikett', models.BooleanField()),
                ('ueberzeit', models.FloatField(default=0.0)),
                ('arbeit', select2.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Arbeit')),
            ],
        ),
        migrations.CreateModel(
            name='EinsatzPlanung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True)),
                ('datum', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'available'), ('auf_anfrage', 'auf_anfrage'), ('not_available', 'not_available')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_color', models.CharField(default='green', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#43843f', 'Green'), ('#4b49ad', 'Blue'), ('#b70130', 'Red'), ('#8d8f01', 'Yellow')], default='#ff0000', max_length=7)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('mwstnr', models.CharField(blank=True, max_length=255, null=True)),
                ('mitarbeitertyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('kalenderzugriff', models.CharField(blank=True, choices=[('BERN', 'BERN'), ('AARAU', 'AARAU'), ('CUT', 'CUT'), ('BERN_CUT', 'BERN_CUT'), ('BERN_AARAU', 'BERN_AARAU'), ('AARAU_BERN', 'AARAU_BERN'), ('BERN_CUT_AARAU', 'BERN_CUT_AARAU')], max_length=255, null=True)),
                ('is_dispo', models.BooleanField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.ImageField(upload_to='transports/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rechnungsdatum', models.DateTimeField()),
                ('arbeit', select2.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Arbeit')),
            ],
        ),
        migrations.CreateModel(
            name='emptySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spesentyp', models.CharField(blank=True, choices=[('Parking', 'Parking'), ('Essen', 'Essen'), ('Verbrauchsmaterial empty', 'Verbrauchsmaterial empty'), ('Andere', 'Andere')], max_length=255, null=True)),
                ('betreff', models.CharField(blank=True, max_length=255, null=True)),
                ('km', models.IntegerField(blank=True, default=50, null=True)),
                ('fahrziel', models.CharField(blank=True, default='Bern', max_length=255, null=True)),
                ('betrag', models.FloatField(default=0)),
                ('arbeitseinsatz', select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spesen', to='demo.Arbeitseinsatz')),
                ('rechnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Rechnung')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.FloatField()),
                ('external', models.FloatField()),
                ('arbeitstyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('arbeit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Arbeit')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Kunde')),
            ],
        ),
        migrations.AddField(
            model_name='einsatzplanung',
            name='mitarbeiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='einsatzplanung',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Team'),
        ),
        migrations.AddField(
            model_name='arbeitseinsatz',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Kunde'),
        ),
        migrations.AddField(
            model_name='arbeitseinsatz',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='arbeitseinsatz',
            name='rechnung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Rechnung'),
        ),
        migrations.AddField(
            model_name='arbeit',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Kunde'),
        ),
        migrations.AddField(
            model_name='abwesenheit',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mid', to='demo.Mitarbeiter'),
        ),
    ]
