# Generated by Django 2.1 on 2018-11-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181105_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitseinsatz',
            name='arbeit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Arbeit'),
        ),
    ]
