# Generated by Django 2.1 on 2018-11-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181105_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.FloatField()),
                ('external', models.FloatField()),
                ('ueberzeit_stunde_internal', models.FloatField()),
                ('ueberzeit_stunde_external', models.FloatField()),
                ('arbeitstyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('arbeit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Arbeit')),
            ],
        ),
        migrations.AlterField(
            model_name='arbeitseinsatz',
            name='ueberzeit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spesen',
            name='spesentyp',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Parking', 'Parking'), ('Essen', 'Essen'), ('Verbrauchsmaterial empty', 'Verbrauchsmaterial empty'), ('Andere', 'Andere')], max_length=255, null=True),
        ),
    ]
