# Generated by Django 2.1 on 2018-11-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20181115_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitseinsatz',
            name='end',
        ),
        migrations.RemoveField(
            model_name='arbeitseinsatz',
            name='start',
        ),
        migrations.RemoveField(
            model_name='einsatzplanung',
            name='end',
        ),
        migrations.RemoveField(
            model_name='einsatzplanung',
            name='start',
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mitarbeiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
