# Generated by Django 2.1 on 2018-12-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20181130_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anzeigeposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbeitstyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anzeigeposition2', to='demo.Mitarbeiter')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Team')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAnzeigeposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbeitstyp', models.CharField(choices=[('KAMERA', 'KAMERA'), ('TON', 'TON'), ('CUT', 'CUT')], max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.Team')),
            ],
        ),
        migrations.AddField(
            model_name='abwesenheit',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('auf_anfrage', 'auf_anfrage'), ('not_available', 'not_available')], default='available', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='spesen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='demo.Spesen'),
        ),
        migrations.AlterField(
            model_name='spesen',
            name='verrechenbar',
            field=models.BooleanField(default=True),
        ),
    ]
