# Generated by Django 2.1 on 2018-12-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20181203_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbeitseinsatz',
            old_name='beschreibung',
            new_name='bemerkung',
        ),
        migrations.RenameField(
            model_name='einsatzplanung',
            old_name='beschreibung',
            new_name='bemerkung',
        ),
        migrations.RenameField(
            model_name='spesen',
            old_name='betreff',
            new_name='bemerkung',
        ),
        migrations.RemoveField(
            model_name='spesen',
            name='fahrziel',
        ),
        migrations.RemoveField(
            model_name='spesen',
            name='km',
        ),
        migrations.AddField(
            model_name='arbeitseinsatz',
            name='fahrziel',
            field=models.CharField(blank=True, default='Bern', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arbeitseinsatz',
            name='km',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
