# Generated by Django 2.1 on 2018-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20181207_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='rechnungsname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitseinsatz',
            name='fahrziel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitseinsatz',
            name='km',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitseinsatz',
            name='ueberzeit',
            field=models.IntegerField(default=0, verbose_name='überzeit'),
        ),
    ]
