# Generated by Django 2.1 on 2018-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20181210_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesen',
            name='betrag',
            field=models.FloatField(default=0, verbose_name='Spesen CHF'),
        ),
        migrations.AlterField(
            model_name='spesen',
            name='spesentyp',
            field=models.CharField(choices=[('-', '-'), ('Parking', 'Parking'), ('Essen', 'Essen'), ('Verbrauchsmaterial empty', 'Verbrauchsmaterial empty'), ('Andere', 'Andere')], default='-', max_length=255),
            preserve_default=False,
        ),
    ]
