# Generated by Django 2.1 on 2019-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=4000, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ACTIV', 'ACTIV'), ('ARCHIV', 'ARCHIV')], max_length=50)),
            ],
        ),
    ]
