# Generated by Django 2.1 on 2019-02-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='head',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
